---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    force: yes
    update_cache: yes

- name: Set Nginx user
  lineinfile: 
    dest: /etc/nginx/nginx.conf
    regexp: "^user"
    line: "user {{ username }};"
    state: present

#- name: Remove default site
#  command: rm -rf /var/www/html  

- name: copy ngix config
  template: 
    src:  nginx-config.j2 
    dest: /etc/nginx/conf.d/{{ website_name }}.conf
  notify: restart nginx
