---
- name: Install mysql
  apt:
    name:  "{{ item }}"
    state: present
    force: yes
    update_cache: yes
  with_items:
    - mysql-server

- name: Make sure pymysql is present
  become: true # needed if the other tasks are not played as root
  pip:
    name: pymysql
    state: present

- name: create database
  mysql_db:
    name: "{{db_name}}" 
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: create mysql user
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{db_user_name}}"
    password: "{{db_user_pass}}"
    priv: "{{db_name}}.*:ALL"
    host: localhost
    state: present
  notify: restart mysql
