---
- name: Upgrade packages
  apt: upgrade=safe
  
- name: Install packages
  apt:
    name: "{{ item.name }}"
    state: present
    update_cache: yes
  with_items:
  - {name: 'fail2ban'}
  - {name: 'git-core'}
  - {name: 'ufw'}
  - {name: 'redis-server'}
  - {name: 'software-properties-common'}
  - {name: 'python3'}
  - {name: 'python3-pip'}
